[2022-02-19 17:11:22,494] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: cassandra_create_test_database_dag.create_table manual__2022-02-19T17:10:15.951066+00:00 [queued]>
[2022-02-19 17:11:22,510] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: cassandra_create_test_database_dag.create_table manual__2022-02-19T17:10:15.951066+00:00 [queued]>
[2022-02-19 17:11:22,510] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 17:11:22,510] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-19 17:11:22,511] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 17:11:22,526] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): create_table> on 2022-02-19 17:10:15.951066+00:00
[2022-02-19 17:11:22,532] {standard_task_runner.py:52} INFO - Started process 2256 to run task
[2022-02-19 17:11:22,535] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cassandra_create_test_database_dag', 'create_table', 'manual__2022-02-19T17:10:15.951066+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/cassandra_create_test_database_dag.py', '--cfg-path', '/tmp/tmphpw864ts', '--error-file', '/tmp/tmpp92na2ar']
[2022-02-19 17:11:22,535] {standard_task_runner.py:77} INFO - Job 76: Subtask create_table
[2022-02-19 17:11:22,603] {logging_mixin.py:109} INFO - Running <TaskInstance: cassandra_create_test_database_dag.create_table manual__2022-02-19T17:10:15.951066+00:00 [running]> on host ff4bf3af9cad
[2022-02-19 17:11:22,728] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cassandra_create_test_database_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T17:10:15.951066+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-19T17:10:15.951066+00:00
[2022-02-19 17:11:22,753] {base.py:79} INFO - Using connection to: id: ***_default. Host: 172.20.0.11, Port: 9042, Schema: None, Login: ***, Password: ***, extra: {}
[2022-02-19 17:11:22,754] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/apache/***/hooks/***.py:123: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2022-02-19 17:11:22,777] {cassandra.py:131} WARNING - Downgrading core protocol version from 66 to 65 for 172.20.0.11:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/***/cluster.html#***.cluster.Cluster.protocol_version
[2022-02-19 17:11:22,785] {cassandra.py:131} WARNING - Downgrading core protocol version from 65 to 5 for 172.20.0.11:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/***/cluster.html#***.cluster.Cluster.protocol_version
[2022-02-19 17:11:22,797] {libevreactor.py:370} ERROR - Closing connection <LibevConnection(139858971530448) 172.20.0.11:9042> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
[2022-02-19 17:11:22,801] {cassandra.py:131} WARNING - Downgrading core protocol version from 5 to 4 for 172.20.0.11:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/***/cluster.html#***.cluster.Cluster.protocol_version
[2022-02-19 17:11:23,213] {cassandra_create_test_database_dag.py:47} INFO - >>>>>>>>>>> Executed: Keyspace and Tables are created
[2022-02-19 17:11:23,213] {python.py:175} INFO - Done. Returned value was: None
[2022-02-19 17:11:23,236] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=***_create_test_database_dag, task_id=create_table, execution_date=20220219T171015, start_date=20220219T171122, end_date=20220219T171123
[2022-02-19 17:11:23,301] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 17:11:23,379] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
