[2022-02-19 16:56:22,078] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task manual__2022-02-19T00:00:00+00:00 [queued]>
[2022-02-19 16:56:22,090] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task manual__2022-02-19T00:00:00+00:00 [queued]>
[2022-02-19 16:56:22,091] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 16:56:22,091] {taskinstance.py:1239} INFO - Starting attempt 15 of 15
[2022-02-19 16:56:22,091] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 16:56:22,107] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): bash_task> on 2022-02-19 00:00:00+00:00
[2022-02-19 16:56:22,111] {standard_task_runner.py:52} INFO - Started process 1158 to run task
[2022-02-19 16:56:22,114] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'configuration_dag', 'bash_task', 'manual__2022-02-19T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/configuration_dag.py', '--cfg-path', '/tmp/tmpne9rlzpg', '--error-file', '/tmp/tmp2epg_4u7']
[2022-02-19 16:56:22,114] {standard_task_runner.py:77} INFO - Job 55: Subtask bash_task
[2022-02-19 16:56:22,210] {logging_mixin.py:109} INFO - Running <TaskInstance: configuration_dag.bash_task manual__2022-02-19T00:00:00+00:00 [running]> on host ff4bf3af9cad
[2022-02-19 16:56:22,274] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=configuration_dag
AIRFLOW_CTX_TASK_ID=bash_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-19T00:00:00+00:00
[2022-02-19 16:56:22,275] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-19 16:56:22,276] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/usr/local/spark/configure.sh ']
[2022-02-19 16:56:22,286] {subprocess.py:85} INFO - Output:
[2022-02-19 16:56:25,636] {subprocess.py:89} INFO - A connection with `conn_id`=spark_default already exists.
[2022-02-19 16:56:29,519] {subprocess.py:89} INFO - [[34m2022-02-19 16:56:29,519[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 16:56:29,526] {subprocess.py:89} INFO - A connection with `conn_id`=minio_default already exists.
[2022-02-19 16:56:32,684] {subprocess.py:89} INFO - [[34m2022-02-19 16:56:32,683[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 16:56:32,689] {subprocess.py:89} INFO - A connection with `conn_id`=cassandra_default already exists.
[2022-02-19 16:56:34,384] {subprocess.py:89} INFO - Installed kernelspec python3 in /home/***/.local/share/jupyter/kernels/python3
[2022-02-19 16:56:34,489] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-19 16:56:34,519] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=configuration_dag, task_id=bash_task, execution_date=20220219T000000, start_date=20220219T165622, end_date=20220219T165634
[2022-02-19 16:56:34,562] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 16:56:34,589] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
