[2022-02-19 17:02:03,694] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task manual__2022-02-19T17:02:01.604725+00:00 [queued]>
[2022-02-19 17:02:03,709] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task manual__2022-02-19T17:02:01.604725+00:00 [queued]>
[2022-02-19 17:02:03,709] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 17:02:03,709] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-19 17:02:03,709] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 17:02:03,722] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): bash_task> on 2022-02-19 17:02:01.604725+00:00
[2022-02-19 17:02:03,726] {standard_task_runner.py:52} INFO - Started process 1468 to run task
[2022-02-19 17:02:03,729] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'configuration_dag', 'bash_task', 'manual__2022-02-19T17:02:01.604725+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/configuration_dag.py', '--cfg-path', '/tmp/tmp1hz_8awm', '--error-file', '/tmp/tmpoic8c9io']
[2022-02-19 17:02:03,730] {standard_task_runner.py:77} INFO - Job 65: Subtask bash_task
[2022-02-19 17:02:03,789] {logging_mixin.py:109} INFO - Running <TaskInstance: configuration_dag.bash_task manual__2022-02-19T17:02:01.604725+00:00 [running]> on host ff4bf3af9cad
[2022-02-19 17:02:03,854] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=configuration_dag
AIRFLOW_CTX_TASK_ID=bash_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T17:02:01.604725+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-19T17:02:01.604725+00:00
[2022-02-19 17:02:03,855] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-19 17:02:03,855] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/usr/local/spark/configure.sh ']
[2022-02-19 17:02:03,865] {subprocess.py:85} INFO - Output:
[2022-02-19 17:02:06,818] {subprocess.py:89} INFO - A connection with `conn_id`=spark_default already exists.
[2022-02-19 17:02:11,185] {subprocess.py:89} INFO - [[34m2022-02-19 17:02:11,185[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 17:02:11,194] {subprocess.py:89} INFO - A connection with `conn_id`=minio_default already exists.
[2022-02-19 17:02:14,877] {subprocess.py:89} INFO - [[34m2022-02-19 17:02:14,876[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 17:02:14,882] {subprocess.py:89} INFO - A connection with `conn_id`=cassandra_default already exists.
[2022-02-19 17:02:16,972] {subprocess.py:89} INFO - Installed kernelspec python3 in /home/***/.local/share/jupyter/kernels/python3
[2022-02-19 17:02:17,097] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-19 17:02:17,144] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=configuration_dag, task_id=bash_task, execution_date=20220219T170201, start_date=20220219T170203, end_date=20220219T170217
[2022-02-19 17:02:17,195] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 17:02:17,241] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
