[2022-02-09 00:01:03,410] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-book-count.spark_job scheduled__2022-02-08T00:00:00+00:00 [queued]>
[2022-02-09 00:01:03,422] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-book-count.spark_job scheduled__2022-02-08T00:00:00+00:00 [queued]>
[2022-02-09 00:01:03,422] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 00:01:03,422] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-02-09 00:01:03,423] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 00:01:03,437] {taskinstance.py:1259} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2022-02-08 00:00:00+00:00
[2022-02-09 00:01:03,441] {standard_task_runner.py:52} INFO - Started process 97 to run task
[2022-02-09 00:01:03,444] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spark-book-count', 'spark_job', 'scheduled__2022-02-08T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/spark-dag.py', '--cfg-path', '/tmp/tmpv27eabj9', '--error-file', '/tmp/tmpf0qdjpqz']
[2022-02-09 00:01:03,445] {standard_task_runner.py:77} INFO - Job 5: Subtask spark_job
[2022-02-09 00:01:03,494] {logging_mixin.py:109} INFO - Running <TaskInstance: spark-book-count.spark_job scheduled__2022-02-08T00:00:00+00:00 [running]> on host b01958778b6e
[2022-02-09 00:01:03,546] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark-book-count
AIRFLOW_CTX_TASK_ID=spark_job
AIRFLOW_CTX_EXECUTION_DATE=2022-02-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-08T00:00:00+00:00
[2022-02-09 00:01:03,555] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://172.24.0.6:7077, Port: None, Schema: , Login: , Password: None, extra: {}
[2022-02-09 00:01:03,556] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://172.24.0.6:7077 --conf spark.master=spark://spark:7077 --name Spark book count --verbose /usr/local/spark/app/spark-book-count.py /usr/local/spark/data/book.txt
[2022-02-09 00:01:03,715] {spark_submit.py:514} INFO - JAVA_HOME is not set
[2022-02-09 00:01:03,730] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 182, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.24.0.6:7077 --conf spark.master=spark://spark:7077 --name Spark book count --verbose /usr/local/spark/app/spark-book-count.py /usr/local/spark/data/book.txt. Error code is: 1.
[2022-02-09 00:01:03,739] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=spark-book-count, task_id=spark_job, execution_date=20220208T000000, start_date=20220209T000103, end_date=20220209T000103
[2022-02-09 00:01:03,753] {standard_task_runner.py:92} ERROR - Failed to execute job 5 for task spark_job
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 182, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.24.0.6:7077 --conf spark.master=spark://spark:7077 --name Spark book count --verbose /usr/local/spark/app/spark-book-count.py /usr/local/spark/data/book.txt. Error code is: 1.
[2022-02-09 00:01:03,776] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-09 00:01:03,818] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
